config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:index, :new, :create, :edit, :update, :show] do
    resources :listings, only: [:edit, :update, :destroy, :show, :new, :own_listings, :create]
    resources :reservations, only: [:edit, :update, :destroy, :show, :new, :own_reservations]
  end

  get "/users/:user_id/listings" => "listings#own_listings", as: "user_own_listings"
  get "/users/:user_id/reservations" => "reservations#own_reservations", as: "user_own_reservations"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings do
    resources :reservations, only: [:create]
  end
  
  resources :reservations, only: [:destroy]

  resources :search, only: [:index]

  root 'welcome#index'

  
end

app/models/listing.rb
class Listing < ActiveRecord::Base
include Filterable
  belongs_to :user
  has_many :reservations
  paginates_per 20
  mount_uploaders :avatars, AvatarUploader

  scope :price, -> (price) { where price: price }
  scope :max_guests, -> (max_guests) { where max_guests: max_guests}
  scope :starts_with, -> (title) { where("title like ?", "#{title}%")}
   
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	before_action :find_listing, only: [:show, :edit, :update]

	def index
		@listings = Listing.all.order(:title).page params[:page]
		# @listings = Listing.where(user_id: params[:id]).order(:title).page params[:page]
	end
	# reference on order: http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-order

		#show own listing
	def own_listings
		@listing = Listing.where(user_id: params[:user_id])
	end

	def new
		@listing = Listing.new
	end

	def create
		#push current_user id into listings table
		@listing = current_user.listings.new(listing_params)
		if @listing.save
			redirect_to listings_path
		end
	end

	def show
		#push @listing info (eg:listing id + current_user id) into reservations table
		@reservation = @listing.reservations.new
	end

	def edit
	end

	def destroy
	end

	def update
		if @listing.update(listing_params)
			flash[:success] = "Successfully updated listing"
			redirect_to @listing
		else
			flash[:danger] = "Error, cannot update listing"
			render :edit
		end
	end

	def find_listing
		@listing = Listing.find(params[:id])
	end

	def listing_params
		params.require(:listing).permit(:title, :description, :max_guests, :price, {avatars: []})
	end

end

app/helpers/listings_helper.rb
module ListingsHelper

end

app/views/listings/_form.html.erb
<%= form_for @listing do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :max_guests %>
    <%= form.number_field :max_guests %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :avatars %>
    <%= form.file_field :avatars, multiple: true %>
  </div>

  <div>
    <%= form.submit "Submit" %>
  </div>

<% end %>

app/views/listings/edit.html.erb
<h1>Edit Listings</h1>
<%= render "listings/form" %>

app/views/listings/index.html.erb
<h1>Listings</h1>

<%= link_to "Create New Listing", new_listing_path %>

<table>
<% @listings.each do |listing| %>
	<tr>
		<td><%= link_to listing.title, listing %></td>
	</tr>
<% end %>
<%= paginate @listings %>
</table>

app/views/listings/new.html.erb
<h1>New Listings</h1>
<%= render "listings/form" %>

app/views/listings/own_listings.html.erb
<% @listing.each do |i| %>

	<h1>Title: <%= i.title%></h1>

	<div>
		<% i.avatars.each do |x| %>
		<%= image_tag x.thumb.url %>
		<% end %>
	</div>

	<p>Posted by:<%= i.user.email%></p>
	<p>Description: <%= i.description %></p>
	<p>Max Guests: <%= i.max_guests %></p>
	<p>Price per night: <%= i.price %></p>
	<%= link_to "Edit", edit_listing_path(i)%>

<% end %>

app/views/listings/show.html.erb
<h1>Title: <%= @listing.title%></h1>

<div>
	<% @listing.avatars.each do |x| %>
	<%= image_tag x.thumb.url %>
	<% end %>
</div>

<p>Posted by:<%= @listing.user.email%></p>
<p>Description: <%= @listing.description %></p>
<p>Max Guests: <%= @listing.max_guests %></p>
<p>Price per night: <%= @listing.price %></p>
<%= link_to "Edit", edit_listing_path(@listing)%>

<%= render "reservations/form" %>