config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:index, :new, :create, :edit, :update, :show] do
    resources :listings, only: [:edit, :update, :destroy, :show, :new, :own_listings, :create]
    resources :reservations, only: [:edit, :update, :destroy, :show, :new, :own_reservations]
  end

  get "/users/:user_id/listings" => "listings#own_listings", as: "user_own_listings"
  get "/users/:user_id/reservations" => "reservations#own_reservations", as: "user_own_reservations"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings do
    resources :reservations, only: [:create]
  end
  
  resources :reservations, only: [:destroy]

  resources :search, only: [:index]

  root 'welcome#index'

  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index
		@search = Listing.filter(params[:listing].slice(:price, :max_guests, :starts_with))
		@results = @search.all.order(:title).page params[:page]
	end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<h1> <%= @search.count %> search(es) found</h1>
<h3> for price at <%= params[:listing][:price] %> with max guests of <%= params[:listing][:max_guests] %></h3>

<h4>Search again?</h4>
<%= form_for(:listing, url: search_index_path, method: :get) do |form| %>
  <div>
  	<%= form.label :price %>
  	<%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :max_guests %>
    <%= form.number_field :max_guests %>
  </div>
  <%= form.submit "Search" %>
<% end %>


<table>
<% @search.each do |result| %>
	<tr>
		<td><%= link_to result.title, result %></td>
	</tr>
<% end %>
<%= paginate @results %>
</table>