config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:index, :new, :create, :edit, :update, :show] do
    resources :listings, only: [:edit, :update, :destroy, :show, :new, :own_listings, :create]
    resources :reservations, only: [:edit, :update, :destroy, :show, :new, :own_reservations]
  end

  get "/users/:user_id/listings" => "listings#own_listings", as: "user_own_listings"
  get "/users/:user_id/reservations" => "reservations#own_reservations", as: "user_own_reservations"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings do
    resources :reservations, only: [:create]
  end
  
  resources :reservations, only: [:destroy]

  resources :search, only: [:index]

  root 'welcome#index'

  
end

app/models/user.rb
require 'byebug'

class User < ActiveRecord::Base
  include Clearance::User
  enum role: { superadmin: 0, moderator: 1, customer: 2 }
  mount_uploader :avatar, AvatarUploader

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.(com)/

	validates :name, presence: true
	validates :email, format: { with: VALID_EMAIL_REGEX, message: 'Please enter a valid email'}
	# validates :password, presence: true
	# validates :gender, presence: true
	# validates :phone_num, presence: true
	# validates :dob, presence: true
	# has_secure_password

	has_many :listings
	has_many :reservations

	has_many :authentications, :dependent => :destroy

	# 1. creates a user object based on info given by provider
	def self.create_with_auth_and_hash(authentication, auth_hash)
		user = User.new(name: auth_hash["info"]["name"],
		 email: auth_hash["extra"]["raw_info"]["email"],
		 remember_token: self.create_remember_token )
		user.authentications<<(authentication)
		user.save
		user
	end

	# 2. fetch fb_token 
	def fb_token
		x = self.authentications.where(:provider => :facebook).first
		return x.token unless x.nil?
	end

	def password_optional?
		true
	end

	# 3. Remember token
	private
	def self.create_remember_token
		 SecureRandom.urlsafe_base64
	end

end

app/controllers/users_controller.rb
# # Inherit from source code Clearance's Users' Controller
# class UsersController < Clearance::UsersController

# 	# Want to redefine user_from_params 
# 	# Hence override default clearance's user's controller
# 	def create
# 		@user = User.new(user_from_params)
# 		if @user.save
# 			sign_in @user
# 			redirect_back_or url_after_create
# 		else
# 			render template: "users/new"
# 		end
# 	end

# 	private #to not make user_from_params a method

# 	def user_from_params
# 		params.require(:user).permit(:name, :email, :password, :gender, :phone_num, :dob)
# 	end
# end

class UsersController < ApplicationController

	def create
		@user = User.new(user_from_params)
		if @user.save
			sign_in @user
			redirect_to user_path(current_user)
			# redirect_back_or url_after_create
		else
			flash[:unsuccessful] = "Please complete all fields"
			render template: "users/new"
		end
	end

	#DRY: find_user params
	before_action :find_user, only: [:show, :edit, :update]
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@reservations = @user.reservations
		render template: "users/show"
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Update profile successful"
			redirect_to @user #@user is user_path @user.id?
		else
			flash[:danger] = "Error in updating user"
			render :edit
		end
	end

	def find_user
		@user = User.find(params[:id])
	end

	private #to not make the below a method

	def user_from_params
		params.require(:user).permit(:name, :email, :password, :gender, :phone_num, :dob)
	end

	def user_params
		params.require(:user).permit(:name, :email, :password, :gender, :phone_num, :dob, :avatar)
	end
end

app/views/users/_form.html.erb
<%= form_for @user do |form| %>

  <div class="name-field">
  	<%= form.label :name %>
  	<%= form.text_field :name %>
  </div>

  <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
  </div>

  <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="gender-field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="phone_num-field">
    <%= form.label :phone_num %>
    <%= form.text_field :phone_num %>
  </div>

  <div class="dob-field">
    <%= form.label :date_of_birth %>
    <%= form.date_field :dob %>
  </div>

    <div class="avatar-field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <!-- create submit button -->
  <%= form.submit "Update Changes" %>

<% end %>

app/views/users/_signupform.html.erb
<%= form_for @user do |form| %>

  <div class="name-field">
  	<%= form.label :name %>
  	<%= form.text_field :name %>
  </div>

  <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
  </div>

  <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="gender-field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="phone_num-field">
    <%= form.label :phone_num %>
    <%= form.text_field :phone_num %>
  </div>

  <div class="dob-field">
    <%= form.label :date_of_birth %>
    <%= form.date_field :dob %>
  </div>

  <!-- create submit button -->
  <%= form.submit "Signup" %>

<% end %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<%= render "users/form" %>

app/views/users/index.html.erb
<table>
	<% @users.each do |user| %>
		<tr>
			<td> <%= link_to user.email, user %> </td>
		</tr>
	<% end %>
</table>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/signupform', object: form %>
  <% end %>
  
</div>

<%= link_to "Sign in with Facebook", "/auth/facebook" %>

app/views/users/show.html.erb
<h2> Profile </h2>

<div>
	<%= image_tag @user.avatar.thumb.url %>
</div>

<p>Email: <%= @user.email %> </p>
<p>Name: <%= @user.name %> </p>
<p>D.O.B: <%= @user.dob %> </p>
<!-- create an edit button based on your override resources in routes.rb-->
<%= link_to "Edit", edit_user_path(@user) %>