config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:index, :new, :create, :edit, :update, :show] do
    resources :listings, only: [:edit, :update, :destroy, :show, :new, :own_listings, :create]
    resources :reservations, only: [:edit, :update, :destroy, :show, :new, :own_reservations]
  end

  get "/users/:user_id/listings" => "listings#own_listings", as: "user_own_listings"
  get "/users/:user_id/reservations" => "reservations#own_reservations", as: "user_own_reservations"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings do
    resources :reservations, only: [:create]
  end
  
  resources :reservations, only: [:destroy]

  resources :search, only: [:index]

  root 'welcome#index'

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pairbnb</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.1.1.js"
   integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
   crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<!-- nav bar: redirect to your views accordingly -->

<h1>PairBnB</h1>
	    <% if signed_in? %>
      Signed in as: <%= current_user.name %> Role: <%=current_user.role %> <br>
      <%= link_to 'Home', root_path %>
      <%= link_to 'User Profile', user_path(current_user) %>
      <%= link_to 'MyListings', user_own_listings_path(current_user) %>
      <%= link_to 'MyBookings', user_own_reservations_path(current_user) %>
      <%= button_to 'Sign Out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Log In', sign_in_path %>
      <%= link_to 'Sign Up', sign_up_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>


<body>

<%= yield %>

</body>
</html>